apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
spec:
  ports:
  - port: {{ .Values.infra.postgresql.containerPort }}
    targetPort: {{ .Values.infra.postgresql.containerPort }}
  selector:
    app: postgresql
  type: ClusterIP