apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
spec:
  clusterIP: None   
  ports:
    - port: {{ .Values.infra.postgresql.containerPort }}
      targetPort: {{ .Values.infra.postgresql.containerPort }}
      name: postgres
  selector:
    app: postgresql
