infra:
  postgresql:
    image: postgres:14.18
    containerPort: 5432
    replicas: 1
    env:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
      POSTGRES_DB: sausage-store
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    storage:
      accessMode: ReadWriteOnce
      size: 1Gi
  mongodb:
    image: mongo:latest
    containerPort: 27017
    replicas: 1
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    storage:
      accessMode: ReadWriteOnce
      size: 1Gi
    