apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{.Values.infra.postgresql.image}}
          ports:
            - containerPort: {{ .Values.infra.postgresql.containerPort }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.infra.postgresql.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.infra.postgresql.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.infra.postgresql.env.POSTGRES_DB }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
spec:
  ports:
  - port: {{ .Values.infra.postgresql.containerPort }}
    targetPort: {{ .Values.infra.postgresql.containerPort }}
  selector:
    app: postgresql
  type: ClusterIP
