-- Таблица с основным каталогом продуктов
CREATE TABLE product (
    id           bigint generated by default as identity,  -- Уникальный идентификатор продукта (автоматически увеличивается)
    name         varchar(255) not null,                    -- Название продукта (обязательно для заполнения)
    picture_url  varchar(255),                             -- Ссылка на изображение продукта
    PRIMARY KEY (id)                                       -- Первичный ключ по полю id
);

-- Вспомогательная таблица с дополнительной информацией о продуктах
CREATE TABLE product_info (
    product_id bigint not null,                            -- Внешний ключ: ID продукта (нет ограничения, просто поле)
    name       varchar(255) not null,                      -- Имя (может дублировать основное имя — потенциально избыточно)
    price      double precision                            -- Цена продукта
);

-- Таблица заказов
CREATE TABLE orders (
    id     bigint generated by default as identity,        -- Уникальный идентификатор заказа
    status varchar(255),                                   -- Статус заказа (например, pending, shipped, cancelled)
    PRIMARY KEY (id)                                       -- Первичный ключ по полю id
);

-- Вспомогательная таблица с датой создания заказа
CREATE TABLE orders_date (
    order_id     bigint not null,                          -- ID заказа (можно использовать как внешний ключ)
    status       varchar(255),                             -- Статус заказа (дублирует поле из orders — потенциально избыточно)
    date_created date default current_date                 -- Дата создания заказа (по умолчанию текущая)
);

-- Таблица связки заказов и продуктов (многие ко многим)
CREATE TABLE order_product (
    quantity   integer not null,                           -- Количество продукта в заказе
    order_id   bigint not null,                            -- ID заказа
    product_id bigint not null                             -- ID продукта
    -- Внешние ключи можно добавить позже через ALTER TABLE
);