env:
    PORT: "8081"
    DB:  mongodb://root:rootpassword@mongodb-service:27017/sausage-store?authSource=admin       #mongodb://reports:reportspassword@mongodb:27017/sausage-store
strategy:
    type: Recreate
revisionHistoryLimit: 15
replicas: 1
annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
image: treasuremeasure/my-go-app:1.0.0
service:
    port: 8082
resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1"